<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>dashboard-server</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.Identity.Web" Version="3.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dashboard.Client\Dashboard.Client.csproj" />
    <ProjectReference Include="..\Dashboard.Shared\Dashboard.Shared.csproj" />
  </ItemGroup>

</Project>
